#To calculate and display perimeter of a rectangle 
L=5
B=3
peri=2*(L+B)
print("perimetre is",peri)

In [1]:
#To calcutalte the area of rectangle
L=20
B=90
area=(L*B)
print("area=",area)

area= 1800

In [2]:
#To calculate area of triangle
B=20
H=77
area=(1/2*B*H)
print("area of triangle=",area)

area of triangle= 770.0

In [1]:
#input length and breadth of rectangle from user calculate and dislpay the result


Length = int(input("Please enter the length of the the rectangle: "))

Breadth = int(input("Please enter the breadth of the rectangle: "))

area =(Length*Breadth)

print("Area =",area)

Please enter the length of the the rectangle: 46
Please enter the breadth of the rectangle: 46
Area = 2116

In [ ]:
Length = int(input("Please enter the length of the the triangle"))
Breadth = int(input("Please enter the breadth of the triangle"))
Height=int(input("please enter the height of the triangle"))
Area = (1/2*Length*Breadth)
Perimeter = (Length+Breadth+Height)
print("Perimeter = ", Perimeter)
print("Area = ", Area)
print("Thanks you fo using")

In [4]:
Length = int(input("Please enter the length of the the triangle:"))
Breadth = int(input("Please enter the breadth of the triangle:"))
Height=int(input("please enter the height of the triangle:"))
Area = (1/2*Length*Breadth)
Perimeter = (Length+Breadth+Height)
print("Perimeter = ", Perimeter)
print("Area = ", Area)
print("THAnk you for using")

Please enter the length of the the triangle:45
Please enter the breadth of the triangle:46
please enter the height of the triangle:37
Perimeter =  128
Area =  1035.0
THAnk you for using

In [5]:
#Arithmetic equation Addation
A=2
B=3
addition=(A+B)
print("addition =",addition)

addition = 5

In [6]:
#Arithmetic equation Subtraction
A=3
B=4
SUBTRACTION=(A-B)
print("subtraction=",SUBTRACTION)

subtraction= -1

In [7]:
#Arithmetic equation MULTIPLICATION
A=5
B=5
MULTIPLICATION=(A*B)
print("PRODUCT=",MULTIPLICATION )

PRODUCT= 25

In [8]:
#Arithmetic equation DIVISION
A=5
B=4
DIVISION=(A/B)
print("DIVISION=",DIVISION)

DIVISION= 1.25

In [9]:
# This function adds two numbers
def add(x, y):
    return x + y

# This function subtracts two numbers
def subtract(x, y):
    return x - y

# This function multiplies two numbers
def multiply(x, y):
    return x * y

# This function divides two numbers
def divide(x, y):
    return x / y


print("Select operation.")
print("1.Add")
print("2.Subtract")
print("3.Multiply")
print("4.Divide")

while True:
    # take input from the user
    choice = input("Enter choice(1/2/3/4): ")

    # check if choice is one of the four options
    if choice in ('1', '2', '3', '4'):
        try:
            num1 = float(input("Enter first number: "))
            num2 = float(input("Enter second number: "))
        except ValueError:
            print("Invalid input. Please enter a number.")
            continue

        if choice == '1':
            print(num1, "+", num2, "=", add(num1, num2))

        elif choice == '2':
            print(num1, "-", num2, "=", subtract(num1, num2))

        elif choice == '3':
            print(num1, "*", num2, "=", multiply(num1, num2))

        elif choice == '4':
            print(num1, "/", num2, "=", divide(num1, num2))
        
        # check if user wants another calculation
        # break the while loop if answer is no
        next_calculation = input("Let's do next calculation? (yes/no): ")
        if next_calculation == "no":
          break
    else:
        print("Invalid Input")

Select operation.
1.Add
2.Subtract
3.Multiply
4.Divide
Enter choice(1/2/3/4): 1
Enter first number:
Invalid input. Please enter a number.
Enter choice(1/2/3/4): w
Invalid Input
Enter choice(1/2/3/4): 3
Enter first number: 3
Enter second number: 54
3.0 * 54.0 = 162.0
Let's do next calculation? (yes/no): no

In [ ]:
# WAP to get the 3 sides of a triangle and deterimne whether is a equilateral oe isosceles or scalen triangle
side1=float(input("Entre length of side1="))
side2=float(input("Entre the length of side2="))
side3=float(input("Entre the length of side3="))
if side1==side2==side3:
    print("Equilateral")
elif side1==side2 or side2==side3 or side2==side3:
    print("isoccles")
else:
    print("scalene")

In [4]:
#to determine the root of a quadratic equation
A=int(input("Entre the value the the coefficient of x^2"))
B=int(input("Entre the value the the coefficient of x"))
C=int(input("Entre the value the the constant"))
D=(B^2)-4*A*C
print("The disrriminat is",D)
if(D==0):
    print("The equation has real and equal roots")
elif(D>0):
    print("The equation has real and distinct roots")
else:(print("The equation has no real roots"))

Entre the value the the coefficient of x^24
Entre the value the the coefficient of x5
Entre the value the the constant8
The disrriminat is -121
The equation has no real roots

In [6]:
#To display the square of even numder 16 to 72
for i in range(16,73,2):
    s=i*i
    print (s)

256
324
400
484
576
676
784
900
1024
1156
1296
1444
1600
1764
1936
2116
2304
2500
2704
2916
3136
3364
3600
3844
4096
4356
4624
4900
5184

In [27]:
# To input a nummber and check it is prime or not
num=int(input("Enter a number"))
limit=int((num+1)/2)
for i in range(2,limit):
    if num%i==0:
        print("it is not a prime numer")
        break
else:
        print("it is a prime number")

Enter a number56
it is not a prime numer

In [28]:
#WAP to read list and display the datatype
list=[5,9,12,31,50,62]
print(list[-4])
print (list[2])

12
12

In [29]:
#WAP to read list and display the datatype
list=[12,"Amit",(25,30),1299]
for i in list:
    print(i,type(i))

12 <class 'int'>
Amit <class 'str'>
(25, 30) <class 'tuple'>
1299 <class 'int'>

In [6]:
# WAP to input some no. repeateadly and print their sum.The program undo when the user say stop"no
ans="y"
sum=0
count=0
while ans=="y":
    n=int(input("Enter number:"))
    if n<0:
        print("Number entered is Zero")
        break
    sum+=n
    count+=1
    ans=input("Do you want to continue")
else:
    print("No of number",count,"sum in",sum)

Enter number:46
Do you want to continuey
Enter number:6
Do you want to continuey
Enter number:56
Do you want to continuey
Enter number:656645
Do you want to continuey
Enter number:5468
Do you want to continuey
Enter number:54645645456
Do you want to continuey
Enter number:54564564
Do you want to continuey
Enter number:97974135
Do you want to continuey
Enter number:449849845134
Do you want to continuen
No of number 9 sum in 504648691510

In [6]:
dict={'Math':55,"Eng":85,"Physic":81,"Chemistry":65,"Ai":98}
print(dict)

{'math': 55, 'eng': 85, 'physic': 81, 'chemistry': 65, 'ai': 98}

In [13]:
for key in dict:
    print(dict[key])

55
85
81
65
98

In [12]:
for key in dict:
    print(key)

math
eng
physic
chemistry
ai

In [15]:
for k in dict:
    print(k)

math
eng
physic
chemistry
ai

In [6]:
import csv
file=open("C:\\Users\\lab-03-19\\Desktop\\student.csv","r")
detail=csv.reader(file)
for rec in detail:
    print(rec)

['Roll no', 'Name', 'Class', 'TrName', '', '', '', '']
['1', 'Akshth', 'ix', 'smaraika', '', '', '', '']
['2', 'Asmitha', 'xi', 'anandita', '', '', '', '']
['3', 'Ankha', 'xii', 'smitha', '', '', '', '']
['4', 'Sruty', 'x', 'abha', '', '', '', '']
['5', 'Ruby', 'xi', 'sandhya', '', '', '', '']
['', '', '', '', '', '', '', '']
['', '', '', '', '', '', '', '']
['', '', '', '', '', '', '', '']
['', '', '', '', '', '', '', '']
['', '', '', '', '', '', '', '']
['', '', '', '', '', '', '', '']
['', '', '', '', '', '', '', '']
['', '', '', '', '', '', '', '']
['', '', '', '', '', '', '', '']

In [4]:
import numpy as np 
ar=np.array([(99,88,77),(44,55,66),(11,22,33)])
print("Arry is\n",ar)

Arry is
 [[99 88 77]
 [44 55 66]
 [11 22 33]]

In [ ]:
import numpy as np
n=int(input("Enter the size of the array"))
ar=np.empty(n)
for i in range(n):
    ar[i]=int(input("Enter an element"))
print ("Array is\n",ar)

46
863
457
61
865
4283
46721
52
87
64
861
24
52783
4283
82
5683
4368
1657
53167
6821
85389641
7235861
45863127

In [5]:
#using data frame
import numpy as np
import pandas as pd
array1=np.array([10,20,30])
array2=np.array([100,200,300])
array3=np.array([-10,-20,-30])
dFrame=pd.DataFrame([array1,array2,array3],columns=["MAths","Physics","Chemistry"],index=["XIA","XIB","XIC"])
print(dFrame)

     MAths  Physics  Chemistry
XIA     10       20         30
XIB    100      200        300
XIC    -10      -20        -30

In [ ]:
#Creating dataframeusing list dicitonaries
import numpy as np
import pandas as pd
listDict=[{'Rajat':90,'Amirata':92,'Meena':89,'Rose':81,'kia':94,}{'Rajat'}]

In [8]:
#
import numpy as np 
import pandas as pd
listDict=[{'Dance':10,'Painting':20},{'Dance':15,'Ai':20},{'Painting':12,'Ai':20}]
a=pd.DataFrame(listDict,index=['X','XI','XII'])
print(a)

     Dance  Painting    Ai
X     10.0      20.0   NaN
XI    15.0       NaN  20.0
XII    NaN      12.0  20.0

In [4]:
a['Ai'].isnull()

X       True
XI     False
XII    False
Name: Ai, dtype: bool

In [6]:
#finding total value of nan values
a.isnull().sum()

Dance       1
Painting    1
Ai          1
dtype: int64

In [9]:
# deleting whole row with nan value
a.dropna()
#replace nan value with 1 
a.fillna(1)

     Dance  Painting    Ai
X     10.0      20.0   1.0
XI    15.0       1.0  20.0
XII    1.0      12.0  20.0

In [10]:
print(a)

     Dance  Painting    Ai
X     10.0      20.0   NaN
XI    15.0       NaN  20.0
XII    NaN      12.0  20.0

In [11]:
a.dropna()

Empty DataFrame
Columns: [Dance, Painting, Ai]
Index: []

In [12]:
#
import numpy as np 
import pandas as pd
listDict=[{'IX':'JAYA','X':'SHANTI','XI':'SRUTHY','XII':'ANAND'},{'IX':'SNITHA','X':'HARIPRIYA','XI':'PRATHA','XII':'SOBHNA'},{'IX':'NOUFIA','X':'REJILA','XI':'LEXSHMI','XII':'JOYTI'}]
Result=pd.DataFrame(listDict,index=['PHYSICS','MATHS','AI'])
print(Result)

             IX          X       XI     XII
PHYSICS    JAYA     SHANTI   SRUTHY   ANAND
MATHS    SNITHA  HARIPRIYA   PRATHA  SOBHNA
AI       NOUFIA     REJILA  LEXSHMI   JOYTI

In [13]:
Result.index

Index(['PHYSICS', 'MATHS', 'AI'], dtype='object')

In [21]:
Result.columns

Index(['IX', 'X', 'XI', 'XII'], dtype='object')

In [16]:
Result.values

array([['JAYA', 'SHANTI', 'SRUTHY', 'ANAND'],
       ['SNITHA', 'HARIPRIYA', 'PRATHA', 'SOBHNA'],
       ['NOUFIA', 'REJILA', 'LEXSHMI', 'JOYTI']], dtype=object)

In [19]:
Result.shape

(3, 4)

In [23]:
Result.head()

             IX          X       XI     XII
PHYSICS    JAYA     SHANTI   SRUTHY   ANAND
MATHS    SNITHA  HARIPRIYA   PRATHA  SOBHNA
AI       NOUFIA     REJILA  LEXSHMI   JOYTI

In [26]:
Result.tail

<bound method NDFrame.tail of              IX          X       XI     XII
PHYSICS    JAYA     SHANTI   SRUTHY   ANAND
MATHS    SNITHA  HARIPRIYA   PRATHA  SOBHNA
AI       NOUFIA     REJILA  LEXSHMI   JOYTI>

In [36]:
Result.to_csv(path_or_buf="C:\\Users\\lab-03-19\\Desktop\\student.csv",sep=',')

In [39]:
import pandas as pd 
import csv
df=pd.read_csv("C:\\Users\\lab-03-19\\Desktop\\student.csv",sep=',',header=0)

In [40]:
df.head()

  Unnamed: 0      IX          X       XI     XII
0    PHYSICS    JAYA     SHANTI   SRUTHY   ANAND
1      MATHS  SNITHA  HARIPRIYA   PRATHA  SOBHNA
2         AI  NOUFIA     REJILA  LEXSHMI   JOYTI

In [ ]:
from sklearn .dataset import load_iris
iris